/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/wenjian.ma/.vim/plugged/perl-5.20.2/miniperl ../bin/enc2xs -Q -o jo_02_t.c -f jo_02_t.fnm
 enc2xs VERSION 2.12
*/
extern encode_t johab_encoding;
