/*
 !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
 This file was autogenerated by:
 /home/wenjian.ma/.vim/plugged/perl-5.20.2/miniperl ../bin/enc2xs -Q -o ma_04_t.c -f ma_04_t.fnm
 enc2xs VERSION 2.12
*/
extern encode_t MacKorean_encoding;
