cache:
 - C:\projects\sources

install:
 - set SOURCES="C:\projects\sources"
 - if not exist "%SOURCES%" mkdir "%SOURCES%"
 - del "%SOURCES%\*.msi"

 # download
 - set PERL530PACKAGE=strawberry-perl-5.30.3.1-64bit-portable.zip

 - if not exist "%SOURCES%\%PERL530PACKAGE%" curl -fsS -o "%SOURCES%\%PERL530PACKAGE%" https://strawberryperl.com/download/5.30.3.1/%PERL530PACKAGE%

 - set PERL530=C:\projects\perl530

 - 7z x "%SOURCES%\%PERL530PACKAGE%" -o"%PERL530%"

 - set OLDPATH=%PATH%
 - set PATH=%PERL530%\perl\bin;%PERL530%\perl\site\bin;%PERL530%\c\bin;%OLDPATH%
 - cd C:\projects\p5-Neovim-Ext
 - cpanm --notest --quiet Dist::Zilla Dist::Zilla::PluginBundle::Author::JACQUESG App::Ack
 - cpanm --quiet --notest Pod::Coverage::TrustPod
 - cpanm --quiet --notest Devel::Cover::Report::Coveralls
 - cpanm --quiet --notest Dist::Zilla::App::Command::cover
 - dzil authordeps --missing | ack -v "inc::" | cpanm --notest --quiet
 - dzil listdeps --missing | cpanm --notest --quiet

build_script:
 - dzil test
